apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sorrykim/cicdtest:blue
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myap-lb
spec:
  ports:
  - name: myapp
    port: 80  # LB 와 연결할 포트
    targetPort: 80
 
  selector:
    app: myapp
  type: LoadBalancer
